export const Animals = [
  {
    id: 1,
    name: "Urubu-Rei",
    description:
      "O urubu-rei é uma ave de rapina impressionante, conhecida por sua plumagem colorida e papel essencial na limpeza dos ecossistemas ao consumir carcaças de animais mortos.",
    images: [
      require("../assets/animals/urubu-rei/1.jpg"),
      require("../assets/animals/urubu-rei/2.jpg"),
      require("../assets/animals/urubu-rei/3.jpg"),
    ],
    sound: false,
  },

  // {
  //   id: 2,
  //   name: "Garça",
  //   description: "A garça é uma ave elegante, frequentemente encontrada em áreas úmidas, conhecida por seu longo pescoço e pernas.",
  //   image: require("../assets/animals/garca.jpg"),
  //   sound: require("../assets/animals/garca.mp3"),
  // },
  // {
  //   id: 3,
  //   name: "Biguá",
  //   description: "O biguá é uma ave aquática excelente mergulhadora, que se alimenta principalmente de peixes.",
  //   image: require("../assets/animals/bigua.jpg"),
  //   sound: require("../assets/animals/bigua.mp3"),
  // },
  // {
  //   id: 4,
  //   name: "Socozinho",
  //   description: "O socozinho é uma pequena ave de hábitos solitários, encontrada em margens de rios e lagoas.",
  //   image: require("../assets/animals/socozinho.jpg"),
  //   sound: require("../assets/animals/socozinho.mp3"),
  // },
  // {
  //   id: 5,
  //   name: "Lavadeira-Mascarada",
  //   description: "A lavadeira-mascarada é uma ave pequena e ativa, conhecida por sua plumagem branca com uma máscara preta ao redor dos olhos.",
  //   image: require("../assets/animals/lavadeira-mascarada.jpg"),
  //   sound: require("../assets/animals/lavadeira-mascarada.mp3"),
  // },
  // {
  //   id: 6,
  //   name: "Frango-d'água",
  //   description: "O frango-d'água é uma ave aquática que vive em pântanos e áreas alagadas, facilmente reconhecível pelo seu comportamento furtivo.",
  //   image: require("../assets/animals/frango-dagua.jpg"),
  //   sound: require("../assets/animals/frango-dagua.mp3"),
  // },
  // {
  //   id: 7,
  //   name: "Pinguim-de-Magalhães",
  //   description: "O pinguim-de-magalhães é uma espécie de pinguim encontrada na América do Sul, conhecida por suas colônias numerosas.",
  //   image: require("../assets/animals/pinguim-de-magalhaes.jpg"),
  //   sound: require("../assets/animals/pinguim-de-magalhaes.mp3"),
  // },
  // {
  //   id: 8,
  //   name: "Pernilongo-de-costas-brancas",
  //   description: "O pernilongo-de-costas-brancas é uma ave pernalta que se alimenta de pequenos invertebrados em águas rasas.",
  //   image: require("../assets/animals/pernilongo-de-costas-brancas.jpg"),
  //   sound: require("../assets/animals/pernilongo-de-costas-brancas.mp3"),
  // },
  // {
  //   id: 9,
  //   name: "Gavião-caramujeiro",
  //   description: "O gavião-caramujeiro é uma ave de rapina que se alimenta quase exclusivamente de caramujos aquáticos.",
  //   image: require("../assets/animals/gaviao-caramujeiro.jpg"),
  //   sound: require("../assets/animals/gaviao-caramujeiro.mp3"),
  // },
  // {
  //   id: 10,
  //   name: "Gavião-do-mangue",
  //   description: "O gavião-do-mangue é uma ave de rapina que habita áreas de mangue e se alimenta de peixes e pequenos invertebrados.",
  //   image: require("../assets/animals/gaviao-do-mangue.jpg"),
  //   sound: require("../assets/animals/gaviao-do-mangue.mp3"),
  // },
  // {
  //   id: 11,
  //   name: "Japim-preto",
  //   description: "O japim-preto é uma ave conhecida por sua plumagem preta e comportamento social complexo, vivendo em grupos.",
  //   image: require("../assets/animals/japim-preto.jpg"),
  //   sound: require("../assets/animals/japim-preto.mp3"),
  // },
  // {
  //   id: 12,
  //   name: "Narceja",
  //   description: "A narceja é uma ave de hábitos migratórios, encontrada em áreas úmidas, com plumagem camuflada que a ajuda a se esconder.",
  //   image: require("../assets/animals/narceja.jpg"),
  //   sound: require("../assets/animals/narceja.mp3"),
  // },
  // {
  //   id: 13,
  //   name: "Atobá",
  //   description: "O atobá é uma ave marinha com grande habilidade de mergulho, conhecida por suas plumagens contrastantes.",
  //   image: require("../assets/animals/atoba.jpg"),
  //   sound: require("../assets/animals/atoba.mp3"),
  // },
  // {
  //   id: 14,
  //   name: "Tuiuiú",
  //   description: "O tuiuiú é a maior ave voadora da América do Sul, conhecida por seu pescoço preto e plumagem branca.",
  //   image: require("../assets/animals/tuiuiu.jpg"),
  //   sound: require("../assets/animals/tuiuiu.mp3"),
  // }
];
